{
  config,
  lib,
  ...
}:

with lib;

let
  cfg = config.hyprland;

  # Helper to parse standard Hyprland monitor strings into Lua tables
  # Expects format: "name,resolution,position,scale[,transform,X]"
  parseMonitorStr = m: let
    parts = splitString "," m;
    name = elemAt parts 0;
    res = elemAt parts 1;
    pos = elemAt parts 2;
    scale = elemAt parts 3;
    # Check if a transform element exists in the string list
    hasTransform = length parts > 5 && elemAt parts 4 == "transform";
    transformVal = if hasTransform then elemAt parts 5 else null;
  in ''
    hl.monitor({
        output = "${name}",
        mode = "${res}",
        position = "${pos}",
        scale = ${scale},
        ${optionalString hasTransform "transform = ${transformVal},"}
    })'';

  monitorLua = concatStringsSep "\n" (map parseMonitorStr cfg.monitors);
in
{
  options.hyprland = {
    monitors = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "DP-1,2560x1440@144,0x0,1"
      ];
    };

    input = {
      sensitivity = mkOption {
        type = types.float;
        default = 0.0;
      };

      kb_layout = mkOption {
        type = types.str;
        default = "us";
      };
    };

    accel_profile = mkOption {
      type = types.str;
      default = "flat";
    };
  };

  config = {
    home.file.".config/hypr/hyprland.lua".text = ''
      -- Load shared static config
      ${builtins.readFile ./hyprland.lua}

      -- =========================
      -- Generated by Nix
      -- =========================

      -- Monitors
      ${monitorLua}

      -- Input
      hl.config({
          input = {
              kb_layout = "${cfg.input.kb_layout}",
              sensitivity = ${toString cfg.input.sensitivity},
              accel_profile = "${cfg.accel_profile}",
          },
      })
    '';

    # Session variables
    home.sessionVariables = {
      XCURSOR_SIZE = "24";
      XCURSOR_THEME = "Bibata-Modern-Classic";
      ELECTRON_OZONE_PLATFORM_HINT = "wayland";
      NIXOS_OZONE_WL = "1";
    };

    # UWSM integration
    xdg.configFile."uwsm/env".text = ''
      source ${config.home.sessionVariablesPackage}/etc/profile.d/hm-session-vars.sh
    '';
  };
}